### ISSUE TITLE
Chunker buf range panic

### ISSUE THREAD

**Issue by duongnhat** [neo4j/neo4j-go-driver#525] opened 2023-08-31 07:13 UTC
panic: runtime error: index out of range [1] with length 0

goroutine 456468686 [running]:
encoding/binary.bigEndian.PutUint16(...)
        /usr/local/go/src/encoding/binary/binary.go:144
github.com/neo4j/neo4j-go-driver/v5/neo4j/internal/bolt.(*chunker).send(0xc000ef4870, {0xe817c0, 0xc00003c0e8}, {0xe7b5c0?, 0xc05e76fb50})
        /home/linuxroot/go/pkg/mod/github.com/neo4j/neo4j-go-driver/v5@v5.11.0/neo4j/internal/bolt/chunker.go:72 +0x3a5
github.com/neo4j/neo4j-go-driver/v5/neo4j/internal/bolt.(*outgoing).send(0xc000ef4870, {0xe817c0?, 0xc00003c0e8?}, {0xe7b5c0?, 0xc05e76fb50?})
        /home/linuxroot/go/pkg/mod/github.com/neo4j/neo4j-go-driver/v5@v5.11.0/neo4j/internal/bolt/outgoing.go:260 +0x34
github.com/neo4j/neo4j-go-driver/v5/neo4j/internal/bolt.(*messageQueue).send(...)
        /home/linuxroot/go/pkg/mod/github.com/neo4j/neo4j-go-driver/v5@v5.11.0/neo4j/internal/bolt/message_queue.go:134
github.com/neo4j/neo4j-go-driver/v5/neo4j/internal/bolt.(*bolt5).Close(0xc07fe26000, {0xe817c0, 0xc00003c0e8})
        /home/linuxroot/go/pkg/mod/github.com/neo4j/neo4j-go-driver/v5@v5.11.0/neo4j/internal/bolt/bolt5.go:925 +0xd6
created by github.com/neo4j/neo4j-go-driver/v5/neo4j/internal/pool.(*server).removeIdleOlderThan
        /home/linuxroot/go/pkg/mod/github.com/neo4j/neo4j-go-driver/v5@v5.11.0/neo4j/internal/pool/server.go:187 +0x22a
FAIL    go-pkg/database/neo4j/test      141.206s
FAIL

**Comment by StephenCathcart** [comment] 2023-08-31 13:27
Hi @duongnhat, I'm assuming this is v5.11.0? Can you share an example of the client-side code you were using that caused this error?

**Comment by robsdedude** [comment] 2023-12-21 10:02
I tried to track down how this unexpected state in the chunker could occur, but without luck.

To be able to locate the issue, more information would be necessary, as @StephenCathcart already wrote. Any combination of the following (preferably all of it) would help:
 * Minimal reproducer.
 * Driver debug logs (including bolt logs) so that we can see what the panicking connection did before things went wrong.
 
 Since there as been no feedback on this issue for over 3 months, I'll close it for now. However, we're still interested in debugging this and happy to re-open it as soon as we have more information.

**Closed as not planned by robsdedude** 2023-12-21 10:02 UTC
