### ISSUE TITLE
Potential Deadlock in Router in clustered environment

### ISSUE THREAD

**Issue by marvinkite** [neo4j/neo4j-go-driver#190] opened 2021-02-15 10:32 UTC
Potential deadlock condition in router:

[https://github.com/neo4j/neo4j-go-driver/blob/4.2/neo4j/internal/router/router.go#L78](https://github.com/neo4j/neo4j-go-driver/blob/4.2/neo4j/internal/router/router.go#L78)

```golang
func (r *Router) getTable(database string) (*db.RoutingTable, error) {
	now := r.now()

	r.dbRoutersMut.Lock() // All my request hangs here now.
	defer r.dbRoutersMut.Unlock()

	dbRouter := r.dbRouters[database]
	if dbRouter != nil && now.Unix() < dbRouter.dueUnix {
		return dbRouter.table, nil
	}

	var (
		table *db.RoutingTable
		err   error
	)

	// Try last known set of routers if there are any
	if dbRouter != nil && len(dbRouter.table.Routers) > 0 {
		routers := dbRouter.table.Routers
		r.log.Infof(log.Router, r.logId, "Reading routing table for '%s' from previously known routers: %v", database, routers)
		table, err = readTable(context.Background(), r.pool, database, routers, r.routerContext)
	}
```

**Neo4j Version:** Aura Cloud  
**Neo4j Mode**: Cluster  
**Driver version**: Go driver 4.2.2  
**Operating System:** Linux,OSX  

With a single instance there is no problem and the service scales well, when connecting to Aura and read mode routes between two nodes after a minute under performance test we hit this problem and we must restart the server. 

Would be nice to add the context to each call so the caller could set the deadline and if any subsequent call times out it could release the lock. 

Instead of this:

```golang
table, err = readTable(context.Background(), r.pool, database, routers, r.routerContext)
```

What we see now all request is queuing up and there is no way yo cancel them and free up those queries which are blocked at the lock but the client already abandoned the response and timed out. 

I could contribute and help to test and fix because this is crucial for us but with this deadlock we can't use this driver.

**Comment by 2hdddg** [comment] 2021-02-15 17:11
I have a look tomorrow at this, it would be really great to have logs for when this happens.

**Comment by marvinkite** [comment] 2021-02-15 17:24
I enabled the logging and  with shorter timeout and also with the context timeout the server survived the deadlock and there were many connection timeout to the Aura server. I will save the logs and sent it.

```golang
driver, err = neo4j.NewDriver(c.neo4jHost, c.neo4jToken,
	CustomLogger(c.log), func(config *neo4j.Config) {
		config.ConnectionAcquisitionTimeout = time.Second * 30
		config.MaxTransactionRetryTime = time.Second * 15
	})
```

I also saw the comments around the many `sync.Lock` in the code so I try to investigate further. What connection setting do you suggest to connect to Aura. The MaxConnectionPoolSize is 100 and I saw it always timedout when it tries to borrow a connection from the pull and many timeout when connection to Aura server but 100 connection should be in the pool in normal operation and not trying to connect again and again. 

Please let me know which configuration you would like me to try and I will generate the logs today or tomorrow.

Thanks,

**Comment by 2hdddg** [comment] 2021-02-15 18:36
Logs with that setting is fine!

**Comment by 2hdddg** [comment] 2021-02-17 07:52
The problem here is not related to the router locking. After seeing example code and logs I'm pretty sure that the problem is that the results are not consumed within the transaction in the client application and that there is a bug in the driver that doesn't discard streams correctly when the number of records are greater than 1000 (fetch size).

**Comment by 2hdddg** [comment] 2021-02-23 07:04
Closing this, two fixes has been merged and released that might be the cause of this,
#194 and #192

**Closed as completed by 2hdddg** 2021-02-23 07:04 UTC
